# Generated by Django 4.1.4 on 2022-12-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='qrCode',
            field=models.ImageField(default=2, upload_to='images'),
            preserve_default=False,
        ),
    ]
