# Generated by Django 3.2.9 on 2021-12-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_no', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('credit', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
